version: 2
jobs:
  one:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: docker --version
      - run:
          name: Android build
          command: |
            python nodejs.py git clone
            python nodejs.py diff apply
            python build.py --target android --arch arm --docker
  two:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: echo "hi"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
