version: 2
jobs:
  one:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Android build
          command: |
            apk update && apk add python
            source j2v8-cli.sh
            nodejs git clone
            nodejs diff apply
            python build.py --target android --arch arm --docker
  two:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: echo "hi"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
